### ISSUE TITLE
PDF does not show images from online

### ISSUE THREAD

**Issue by axiom88-guru** [eKoopmans/html2pdf#141]
Hi , 
I use Angular 5 and this is used for my Angular method.

```
        var element = document.getElementById('document');
        var opt = {
            margin:       [10, 0, 10, 0],
            filename:     'document.pdf',
            image:        { type: 'jpeg', quality: 0.98 },
            html2canvas:  { scale: 2 },
            jsPDF:        { unit: 'mm', format: 'letter', orientation: 'portrait' }
        };
        html2pdf().from(element).set(opt).save();
```

After exporting a pdf, I am unable to see any images from online but it shows locally stored images. 
Here is the example of image online. 
https://s3.amazonaws.com/images.anterasoftware.com/5b6c5886622d5Screen_Shot_2018-06-27_at_10.37.03_AM.png

Please help, @eKoopmans 
Regards.

**Comment by axiom88-guru** [comment]
I am trying to render cross-domain image which is exactly stored in amazon s3.  Please find the attached screenshot , any advice would be appreciated.
![image](https://user-images.githubusercontent.com/19179511/43980703-dff8c038-9cf7-11e8-9191-802b7328b136.png)

**Comment by solomondn** [comment]
I got the same issue. But it's quite different. PDF created but it show empty space, not image.

**Comment by PhilipTKC** [comment]
It's not the best solution, But if you can convert your Image to Base64.

**Comment by dandocan** [comment]
I have the same issue as solomondn on React and can't work around it since I can't store the images locally.

**Comment by dandocan** [comment]
`printDocuments() {
        var opt = {
            margin: 1,
            pagespilt: true,
            filename: 'download.pdf',
            image:{type:'png'},
            // html2canvas: {scale: 2},
            // jsPDF:{ unit: 'in', format: 'letter', orientation: 'portrait' }
        }
        var input = document.getElementById("pdfContainer");
        console.log(input)
        html2pdf(input, opt)
    }`
this being my code

**Comment by dandocan** [comment]
//this is my code for it
printDocuments() {
        var opt = {
            margin: 1,
            pagespilt: true,
            filename: 'download.pdf',
            image:{type:'png'},
            html2canvas: {scale: 2},
            // jsPDF:{ unit: 'in', format: 'letter', orientation: 'portrait' }
        }
        var input = document.getElementById("pdfContainer");
        console.log(input)
        html2pdf(input, opt)
    }

**Comment by PhilipTKC** [comment]
I am also having a similar issue. Wont detect any external images at all.

As a workaround you can convert your images to Base64.

**Comment by PhilipTKC** [comment]
I am also having a similar issue. Wont detect any external images at all.

As a workaround you can convert your images to Base64

For example.

Using
```
<template>
  <div id="sheet">
    <p>Hello
      <img src="{link to external Image}" />
    </p>
  </div>

  <button click.delegate="download()">Download</button>
</template>
```

Yields

```
489ms html2canvas: Finished loading 0 images []
```

Using Base64
```
  <div id="sheet">
    <p>Hello
      <img src="{image as base64}" />
    </p>
  </div>

```

```
272ms html2canvas: Added image data:image/gif;base64,...........
```

@axiom88-guru Does this do anything for you?

```
<img crossorigin="*" src="https://s3.amazonaws.com/images.anterasoftware.com/5b6c5886622d5Screen_Shot_2018-06-27_at_10.37.03_AM.png" />
```

Once again, You can only retrieve images with servers that have CORS enabled.

**Comment by axiom88-guru** [comment]
@PhilipTKC  thanks for your response. 
I already solved this problem by enabling CORS on S3.  Thanks.

**Comment by khaukheng** [comment]
> I got the same issue. But it's quite different. PDF created but it show empty space, not image.

I got the exact same issue with solomondn, have you fix it?

**Comment by gvsakhil** [comment]
@bdwellons can u share me the code u used to convert images to base64?

**Comment by Paytah232** [comment]
@bdwellons +1 to the code. I tried in JS doing img.src=<base64>, the html page showed the image correctly, but it still wouldn't show in the generated PDF.

**Comment by brunaschneiders** [comment]
> @bdwellons +1 to the code. I tried in JS doing img.src=, the html page showed the image correctly, but it still wouldn't show in the generated PDF.

Hi! do you have the code that can be used to convert images to base64?

**Comment by InSyn** [comment]
Try to specify "allowTaint" parameter to "true" in html2canvas object

opt = {
          margin: 0,
          filename: "myfile.pdf",
          image: { type: "jpeg", quality: 0.98 },
          html2canvas: {
            allowTaint: true,
            scale: 2
          },
          jsPDF: {
            unit: "in",
            format: "a4",
            orientation: this.setup.orientation
          }
        };

**Comment by Ankit-Mishra07** [comment]
Thank you @PrasanthPerumalsamy

**Comment by iSurojiddin** [comment]
function exportToPDF() {
  let elem = document.getElementById('pdf')
  let opt = {
    filename: 'sold_products.pdf',
    image: { type: 'jpeg' },
    html2canvas: { useCORS: true, scale: 2 }
  }
  html2pdf().from(elem).set(opt).save()
}

**Comment by cgutierrez365** [comment]
To anyone wondering how to enable CORS (Cross-origin resource sharing) on Firebase storage so your app can access photos saved there using this plugin by simply writing something like `<img src=https://firebasestorage.googleapis.com/path-to-image>`, follow [these instructions](https://firebase.google.com/docs/storage/web/download-files#cors_configuration) to enable CORS. You will need to create a cors.json file with the contents in the provided example (or replace the `*` in `"origin": ["*"]` with the path to your app's domain. From what I understand specifying the specific domain is more secure because otherwise any domain, including malicious ones, can access data from your firebase storage). You can keep the cors.json file in your project's root directory. Then after installing the gsutil command line tool, you can run `gsutil cors set cors.json gs://<your-cloud-storage-bucket>` like the instructions say. You can find what `<your-cloud-storage-bucket>` is for your specific project by logging into your project on [console.firebase.google.com](console.firebase.google.com) and navigating to Storage>Files and copying what should look similar to `gs://exampleproject.appspot.com`.

![storage bucket](https://github.com/eKoopmans/html2pdf.js/assets/47370655/661f6eed-909d-4ea0-b04b-e57f3fa92370)

Here's a link to an additional resource you may find useful: [https://stackoverflow.com/a/37765371/17246058](https://stackoverflow.com/a/37765371/17246058)

**Comment by AhmedMuhammedElsaid** [comment]
I had the same issue and the following configs work with me just fine
// @ts-ignore
import("html2pdf.js").then(html2pdf => {
html2pdf
.default()
.from(wrapper)
.set({
filename: "analytics.pdf",
html2canvas: { dpi: 300, letterRendering: true, useCORS: true, scale: 2, },
jsPDF: { unit: "in", format: "letter", orientation: "portrait" },
pagebreak: { mode: "avoid-all", before: "#page2el" },
image: { type: "jpeg", quality: 1 },
})
.save()
