### ISSUE TITLE
Adding support for jsPDF's autoprint option

### ISSUE THREAD

**Issue by onearmfrog** [eKoopmans/html2pdf#29]
Hi, first of all if you don't mind I'll use this issue to praise you. This custom build has saved me from having a meltdown after hours of fiddling with html2canvas & jsPDF.

It would be great if you could add jsPDF's autoPrint option which can be useful in some cases.

This is how I implemented it, not sure if it's the best solution, but it works for me:

`	if (opt.autoPrint) { 
		pdf.autoPrint();
		window.open(pdf.output('bloburl'), '_blank');
		return;
	}`

**Comment by eKoopmans** [comment]
Hi @onearmfrog, thanks for the comment! And I'm glad the package helped you out.

Rather than incorporating too many specific features of jsPDF/html2canvas into this package, my plan is to expose the jsPDF object and let users make whatever modifications they want to it (like adding the `pdf.autoPrint()` option). There's a branch right now called 'pdf-callback' that does just that, described a bit better [here](https://github.com/eKoopmans/html2pdf/issues/14#issuecomment-318798955).

Soon (very soon I hope!) I'll be making a bit of an overhaul to the master branch to clean up the API and work that in. Stay tuned!

**Comment by onearmfrog** [comment]
Sounds awesome! Thanks for the hard work.

**Comment by eKoopmans** [comment]
Hi, I have just pushed a new branch, [new-api](https://github.com/eKoopmans/html2pdf/tree/new-api), which is ready for testing! [The readme](https://github.com/eKoopmans/html2pdf/tree/new-api#advanced-usage) has all the information on the new API. Please let me know if there are any problems with it - I want to make sure it's stable before merging into master!

For this specific request, you could add your custom autoPrint settings after the PDF object is created:

```js
html2pdf().from(element).toPdf().get('pdf').then(function (pdf) {
  pdf.autoPrint();
  window.open(pdf.output('bloburl'), '_blank');
});
```

**Comment by eKoopmans** [comment]
Hi, closing as resolved by the v0.9.0 new API.

**Comment by vreans08** [comment]
Hi @eKoopmans ,

This works perfectly in chrome and other desktops/Mac browsers.

But the same is not working in android devices. The blob gets downloaded instead of the print window.
Is there any way we can achieve the same in android and iOS chrome/Firefox will be highly appreciated.

**Comment by Bolofis** [comment]
Guys  I have created a pdf using html2pdf from two different pages using base64 string yet I am when I am running my aspnetMVC from a smartphone through QRCode the base64 string is not generated.
Any suggestions? Is the file too big for the browser of a mobile phone any thoughts?
