### ISSUE TITLE
Can not display image on pdf

### ISSUE THREAD

**Issue by SongPaul** [eKoopmans/html2pdf#35]
Hi, I wanna use this lib..
but have some problem..
becouse, Can't display url image... 
how can i fix it....

please check here
https://jsfiddle.net/syy12/7w9nudsc/

**Comment by eKoopmans** [comment]
Hi @SongPaul, my guess is this is a problem with cross-domain images, which cause issues because of security settings on HTML5 canvases. You need to use special options in html2canvas to enable CORS and/or request the image through a proxy. There's more info on that [here](https://github.com/niklasvh/html2canvas/issues/1077#issuecomment-302484496).

**Comment by SongPaul** [comment]
@eKoopmans Thanks. I resolved this issue. but I got a one more issue 

all graph text looks overapped.
how can i fix it?
![screenshot 16](https://user-images.githubusercontent.com/8253615/30622774-bd47ac60-9dee-11e7-99e0-568ed1b26382.png)

**Comment by eKoopmans** [comment]
Huh, I'm really not sure what would cause that, sorry!

**Comment by eKoopmans** [comment]
Closing this issue, let me know if you still need help with it!

**Comment by prabhuraj2018** [comment]
@SongPaul Could you please let me know how did you fix that issue?...I'm also facing the same issue due to CORS but even after using useCORS and proxy properties still not able to resolve the issue....
