### ISSUE TITLE
Canvas size in PDF with custom html2canvas

### ISSUE THREAD

**Issue by albancho** [eKoopmans/html2pdf#39]
Hey there,

I'm trying to generate a PDF using your plugin, which seems to fit exactly what I wish to do, but had some troubles in the output.
I first used the original dependencies (jsPdf & html2canvas) and had a bad quality PDF (text was blurred).
So I've included your custom dependencies in my project (in your vendor folder), and noticed the new "dpi" feature which solved my blur problem (great !).
But now, the generated canvas is trimmed (which was not the case before updating dependencies).
If I set an height and width in html2canvas, about 1/4 of the right side of the pdf is trimmed (so 1/4 of the content was missing and replaced with a large blank line).
If I don't set any width/height, the same part is trimmed, but not filled with blank (actually, the canvas is bigger than the pdf, so 1/4 of the bottom of 1st page goes at the top of page 2, and 1/4 of the right edge does not appear in the pdf).

Here is a CSS sample:
```
#pdfContent {
    border: solid 1px black;
    background-color: white;
}
.page {
    height: 1448px;
    width: 1024px;
}
```

HTML:
```
<div id="pdfContent" class="container noPadding">
  <div class="page bluebg">
    <div class="cadre" style="text-align: center">
      <span>Beginning of the PDF (centered) 0123456789012345678901234567890123456789012345678901234567890123456789</span><br/>
    </div>
    <div class="cadre">
      <span class="e">this is Elec text</span><br/>
      <span class="g">this is  Gaz text</span><br/>
      <span class="b">this is  Bi text</span><br/>
      <span class="bold">this is a bold text</span><br/>
      <span>an img containing SVG asset: 
        <img id="img_picto_header_gauche" src="assets/img/Metiers/ic_BCHTR_e.svg" style="width: 40px; height: 40px"/>
      </span><br/>
      <span>another img containing SVG asset: 
        <img id="img_picto_footer_centre" src="assets/img/Metiers/ic_ENTCORP_e.svg" style="width: 40px; height: 40px"/>
      </span><br/>
      <br/>
    </div>
  </div>
  <div class="page" style="text-align: center">
    <span>Page 2 !</span><br/>
  </div>
  <div class="page redbg" style="text-align: center">
    <span>Page 3 !</span>
  </div>
</div>
```

TS code:
```
    let nbPages = 3;
    let sourceHtml = $('#pdfContent');

    // doc html2pdf: https://github.com/eKoopmans/html2pdf
    html2pdf(sourceHtml[0], {
      margin: 1,
      filename: 'test-' + DateUtils.generateTimeStamp() + '.pdf',
      image: { type: 'jpg' },
      html2canvas: { dpi: 192, letterRendering: true, width: 1024, height: 1448 * nbPages },
      jsPDF: { unit: 'pt', format: 'a4', orientation: 'portrait' }
    });
```

here is the generated HTML (in a browser):
![browser_view_html](https://user-images.githubusercontent.com/32709248/31486729-b65364ca-af38-11e7-9cfb-8f4417c8678d.jpg)

here is the generated PDF when no width/height is specified in html2canvas (the bad quality is from my screenshot, not from the pdf):
![canvas-bigger-than-pdf](https://user-images.githubusercontent.com/32709248/31486761-cdde5564-af38-11e7-8675-78c8f365d7b8.jpg)

here is the generated PDF when width/height is specified in html2canvas, which is the same as the CSS size (the bad quality is from my screenshot, not from the pdf)
![canvas-trimmed](https://user-images.githubusercontent.com/32709248/31486797-e43b0e10-af38-11e7-95b6-afbc90042785.jpg)

I'm having troubles debugging the minified version of html2canvas including your dpi patch, so I wonder if you have the unminified version so I could find out why the canvas is trimmed ?
Or if you have any idea yourself about the issue ?

Thanks,
Alban

**Comment by eKoopmans** [comment]
Hey @albancho! Sorry about the wait. First things first, `jsPDF` in the vendor folder is now straight from their official dist, so you can check the unminified version there: [jspdf.debug.js](https://github.com/MrRio/jsPDF/blob/master/dist/jspdf.debug.js).

Now, about your issue - it's interesting. Actually, I'm surprised it was working fine with the original version of html2canvas! Here's how html2pdf works:

1. html2pdf copies your elements into an invisible div that is the width of one page (using the units and dimensions that are sent to jsPDF, minus your margins).
2. It converts that div into an image (using html2canvas).
3. It slices that image up into single pages and adds them into a jsPDF.

So at the first step, if your element has a fixed width (instead of `width: 100%`) that is larger than the width of the page, then it will get cropped off. I believe that's what's happening here. A4 width is 210mm = 595.28pt = 794px (minus 2pt more for your margins), and your `.page` is set to `1024px`.

I know none of that is very obvious, from just using the package! I think I need to make changes to accommodate more different use cases like yours.

**Comment by eKoopmans** [comment]
Closing, let me know if you're still having issues!

**Comment by mark1828** [comment]
I still have the issue! I already wrote a question on stack overflow about it, but no one answered yet, can someone help me please?

My question: https://stackoverflow.com/questions/59159579/html2canvas-jspdf-cut-off-image

**Comment by CrazyOvi** [comment]
> Closing, let me know if you're still having issues!

Can I ask if the "Safari problem" has a solution? - if I create a PDF largen then 4 pages, it gives me a blank pdf, if lower, it generates perfectly...

**Comment by mrcgilencnto** [comment]
> 
can you convert it into code?
