### ISSUE TITLE
Single page height / width specification

### ISSUE THREAD

**Issue by devxpy** [eKoopmans/html2pdf#81]
Hello, i want to fit exactly `x` no of images in `1` page. 

I designed an algorithm that fits the images on a single browser window, keeping intact their orignal ppi. 

It works good when viewed in browser, but the pdf page has different height. Can you please provide me with the height / width of the page you generate?

**Comment by eKoopmans** [comment]
Hi @devxpy, sorry for the *long* delay.

There have been a few requests for generating single-page PDFs, I haven't had a chance to add that feature yet. Currently, html2pdf clones the elements into a container with a width defined by your jsPDF page width, and lets the elements reflow so they fit nicely onto the page width.

**Comment by devxpy** [comment]
Did you mean to say
> elements reflow so they fit nicely onto the page __height__ 
?

**Comment by eKoopmans** [comment]
No, it sets the width (based on jsPDF settings), allowing elements to reflow based on that width. For instance if you had two divs with `width: 500px` and `float: left` and a page-width of 800px, those elements would reflow to be below each other rather than side-by-side. Another example would be if an element was set to `width: 100%`, it would fill the page width.

Page height is determined by jsPDF settings, and # of pages is simply based on the total height of the reflowed elements.

**Comment by devxpy** [comment]
Ah, got it.

> based on jsPDF settings
So where can I specify that height/width?
I can't find the API to do that.

**Comment by eKoopmans** [comment]
Hi @devxpy, some info:

- [the jsPDF option in html2pdf](https://github.com/eKoopmans/html2pdf#options)
- [jsPDF parameters (orientation, unit, format)](https://rawgit.com/MrRio/jsPDF/master/docs/jsPDF.html)
- [jsPDF format options](https://rawgit.com/MrRio/jsPDF/master/docs/jspdf.js.html#line47)

So you can specify the jsPDF page size to A4 like so:

```js
html2pdf(element, {
    jsPDF: { format: 'a4' }
});
```

Note that `format` will also accept an array of `[length, width]` values like `[595.28, 841.89]`, but those values are in *points*, which you would need to convert from pixels or any other unit (1 pixel = 72/96 points).

**Comment by devxpy** [comment]
Thanks for the explanation.
