### ISSUE TITLE
Borders hidden

### ISSUE THREAD

**Issue by MikeGsus** [eKoopmans/html2pdf#95]
Hi, I'm exporting a HTML Table and some inputs to PDF, but when it renders don't shows the borders of the elements. It looks like this: 
![captura de pantalla 25](https://user-images.githubusercontent.com/19364241/37782940-d05aeb0e-2db9-11e8-9c8a-adf2c32eaa6c.png)

When the HTML looks: 
![screenshot-2018-3-22 intrainingls](https://user-images.githubusercontent.com/19364241/37783037-0a5cb6a2-2dba-11e8-922e-2995470196d2.png)

I just want to display the element's borders in the PDF as the HTML.

**Comment by MikeGsus** [comment]
If is usefull to somebody, I just do wider the borders, so they appear at PDF.

**Comment by weixiongBirnary** [comment]
I have the same problem, can u tell me how to fix this

**Comment by DaddyWarbucks** [comment]
I am also experiencing this issue. Some borders display properly, some do not. I cannot discern what makes the difference in them displaying or not. I have tried making the borders wider and darker, but that did not help. Thanks for any help!

Using version `0.9.3`.

**Comment by DaddyWarbucks** [comment]
After some further investigation, I now realize this is likely an issue with `html2canvas` and not `html2pdf` directly. The issue appears to be solved over in that library according to this: https://github.com/niklasvh/html2canvas/pull/2010. And that makes sense because I am using "partial" borders as that issues outlines (via Bootstrap .border-bottom, .border-right, etc).

This library is still using `"html2canvas": "^1.0.0-alpha.12"` an alpha version of the 1.0 release. I suspect that updating to the latest production release of `1.1.1` would solve this issue. 

Is there anything I can do to help make this happen?

**Comment by DaddyWarbucks** [comment]
I have created a jsfiddle here: https://jsfiddle.net/0tk5mdax/26/. The fiddle is an exact copy of my HTML that I am trying to convert. And you can see it is rather complex as far as borders go.

It seems to work as expected. Which is good news! 

But, I am still unable to get this working in my own application. I have even stripped everything out that I can think of, including custom Bootstrap code/themes, third party CSS, plugin/extension CSS, etc. So I am unclear why this works in isolation in the fiddle but not in "isolation" (as much as I can) in my own app. I have also tried Safari, Chrome, and FF but all seem to fail.

Any help is appreciated. Thanks!
